### ISSUE TITLE
bug: can't instal cL

### ISSUE THREAD

**Issue by 7uyih** [SallaApp/Salla-CLI#43]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

![Welcome - salla - Visual Studio Code 09_04_45 11_04_25 م](https://github.com/SallaApp/Salla-CLI/assets/97174933/65a87a1c-fbab-4470-9377-f6894c6485ba)

I did not know how to open the file in the terminal, so I opened the file on vscode and put the CLI install command :  "npm install @salla.sa/cli -g"and this message that appeared to me

### Expected Behavior

CLI download process is completed successfully

### Steps to Reproduce

..

### Salla Info

i didnt have

### Additional Information

.

**Comment by abdulrhman-developer0** [comment]
'@' is a spicsial character at terminal or powershell
you can wrap the package name by ""
example:
  npm install "@salla.sa/cli" -g

**Comment by fathidevs** [comment]
I had the same issue on my  (WINDOWS) and turned out the `npm` wasn't installed properly.
here is what I did to fix it:

1. uninstalled nodejs.
2. deleted all these directories:

`C:\Users\<your-username>\AppData\Roaming\npm`
`C:\Users\<your-username>\AppData\Roaming\node`
`C:\Program Files\nodejs`
`C:\ProgramData\chocolatey`
`C:\ProgramData\ChocolateyHttpCache`

3. restarted my pc
4. installed chocolatey
5. re-installed nodejs.

then ran the command: `npm install @salla.sa/cli -g`
now it's working
